version: '3'

services:
  yanews:
    build:
      context: .
      dockerfile: docker/yanews.dockerfile
    container_name: yanews
    depends_on:
      - postgres
      - redis
    environment:
      DEV_DB_HOST: "postgres"
      REDIS_HOST_SIDEKIQ: "redis://redis:6379/0"
      REDIS_HOST_CABLE: "redis://redis:6379/1"
    ports:
      - "3000:3000"
    volumes:
      - .:/ya_news

  postgres:
    image: postgres
    container_name: yanews_postgres
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: yanews_redis
    ports:
      - "6379:6379"
    restart: unless-stopped


